apiVersion: apps/v1
kind: Deployment

metadata:
  name: production-platform-api
  labels:
    app: production-platform-api

spec:
  replicas: {{ .Values.replicaCount }}

  revisionHistoryLimit: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: production-platform-api

  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}

      labels:
        app: production-platform-api

    spec:
      containers:
        - name: production-platform-api

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          envFrom:
            - configMapRef:
                name: production-platform-config

            - secretRef:
                name: production-platform-secret

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}

          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}

          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}